id: /subscriptions/d71f6c1b-d841-4284-a9d9-0a425fe3e358/resourceGroups/alpinely/providers/Microsoft.App/containerapps/counta
identity:
  type: None
location: West US 2
name: counta
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: Ignore
      corsPolicy: null
      customDomains:
      - bindingType: SniEnabled
        certificateId: /subscriptions/d71f6c1b-d841-4284-a9d9-0a425fe3e358/resourceGroups/alpinely/providers/Microsoft.App/managedEnvironments/managedEnvironment-alpinely-846d/managedCertificates/api.counta.alpinely.ai-managede-240218110657
        name: api.counta.alpinely.ai
      exposedPort: 0
      external: true
      fqdn: counta.proudsky-0dc6421d.westus2.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions:
        affinity: none
      targetPort: 8000
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: null
    registries:
    - identity: ''
      passwordSecretRef: cac5f5b3589eacrazurecrio-cac5f5b3589eacr
      server: cac5f5b3589eacr.azurecr.io
      username: cac5f5b3589eacr
    secrets:
    - name: cac5f5b3589eacrazurecrio-cac5f5b3589eacr
    service: null
  customDomainVerificationId: 6911DF0DA2EE79E23485988725B67A181C976178207162051DBE8A04D4378982
  environmentId: /subscriptions/d71f6c1b-d841-4284-a9d9-0a425fe3e358/resourceGroups/alpinely/providers/Microsoft.App/managedEnvironments/managedEnvironment-alpinely-846d
  eventStreamEndpoint: https://westus2.azurecontainerapps.dev/subscriptions/d71f6c1b-d841-4284-a9d9-0a425fe3e358/resourceGroups/alpinely/containerApps/counta/eventstream
  latestReadyRevisionName: counta--eeq0apj
  latestRevisionFqdn: counta--eeq0apj.proudsky-0dc6421d.westus2.azurecontainerapps.io
  latestRevisionName: counta--eeq0apj
  managedEnvironmentId: /subscriptions/d71f6c1b-d841-4284-a9d9-0a425fe3e358/resourceGroups/alpinely/providers/Microsoft.App/managedEnvironments/managedEnvironment-alpinely-846d
  outboundIpAddresses:
  - 20.99.170.216
  - 20.99.171.18
  - 20.99.170.250
  - 20.99.170.223
  - 20.99.170.208
  - 20.99.170.164
  - 20.99.170.240
  - 20.99.170.49
  - 20.99.171.11
  - 20.99.170.181
  - 20.69.82.220
  - 20.69.83.13
  - 20.69.83.5
  - 20.69.83.46
  - 20.115.200.188
  - 20.115.201.160
  - 20.115.201.51
  - 20.115.201.152
  - 20.115.201.28
  - 20.115.201.167
  - 20.115.194.124
  - 20.115.194.128
  - 20.115.194.137
  - 20.115.194.126
  - 20.29.134.80
  - 20.29.134.79
  - 20.29.134.41
  - 20.29.134.75
  - 20.29.132.146
  - 20.29.134.12
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - env:
      - name: PROJECT_NAME
        value: fastapi-sqlmodel-alembic
      - name: FIRST_SUPERUSER_PASSWORD
        value: admin
      - name: FIRST_SUPERUSER_EMAIL
        value: admin@admin.com
      - name: ENCRYPT_KEY
        value: TshgGacKPYrm35m89UqbRg46JAbUm2yRtxOCQFdqa3w=
      - name: SECRET_KEY
        value: 09d25e0sas4faa6c52gf6c818166b7a9563b93f7sdsdef6f0f4caa6cf63b88e8d3e7
      - name: BACKEND_CORS_ORIGINS
        value: '["*"]'
      - name: DATABASE_HOST
        value: alpinely20240217.postgres.database.azure.com
      - name: DATABASE_USER
        value: alpinely
      - name: DATABASE_PASSWORD
        value: AJsf9ahsdhfa1_nas
      - name: DATABASE_NAME
        value: counta
      - name: DATABASE_CELERY_NAME
        value: celery_schedule_jobs
      - name: DATABASE_PORT
        value: '5432'
      - name: EXT_ENDPOINT1
        value: 127.0.0.1
      - name: LOCAL_1
        value: localhost
      - name: LOCAL_2
        value: 127.0.0.1
      - name: REDIS_HOST
        value: alpinely.redis.cache.windows.net
      - name: REDIS_PORT
        value: '6380'
      - name: REDIS_PASS
        value: jTplhZ0Pd7xaMH868UVgbrU35GhPh70VXAzCaOYrTqU=
      - name: MINIO_URL
        value: storage.localhost
      - name: MINIO_BUCKET
        value: fastapi-minio
      - name: MINIO_ROOT_USER
        value: minioadmin
      - name: MINIO_ROOT_PASSWORD
        value: minioadmin
      - name: WHEATER_URL
        value: https://wttr.in
      - name: OPENAI_API_KEY
        value: ''
      image: cac5f5b3589eacr.azurecr.io/counta:cli-containerapp-20240218023855264726
      name: counta
      probes: []
      resources:
        cpu: 1
        ephemeralStorage: 4Gi
        memory: 2Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      maxReplicas: 10
      minReplicas: 1
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: []
  workloadProfileName: Consumption
resourceGroup: alpinely
systemData:
  createdAt: '2024-02-16T20:09:17.8645431'
  createdBy: gjj2684@gmail.com
  createdByType: User
  lastModifiedAt: '2024-02-18T11:35:15.8895862'
  lastModifiedBy: gjj2684@gmail.com
  lastModifiedByType: User
type: Microsoft.App/containerApps
